version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    expose:
      - "8080"

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\""]
      interval: 60s
      timeout: 5s
      retries: 5

volumes:
  database:
